services:
  tms:
    image: tms-image

    networks:
      - caddy
      - default

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    environment:
      DJANGO_SETTINGS_MODULE:

      SECRET_KEY:
      DEBUG:
      ALLOWED_HOSTS:
      CSRF_TRUSTED_ORIGINS:

      DB_ENGINE:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      DB_HOST=postgres:
      DB_PORT=5432:

      EMAIL_BACKEND:
      EMAIL_HOST:
      EMAIL_PORT:
      EMAIL_USE_TLS:
      DEFAULT_FROM_EMAIL:

      PGHERO_USERNAME:
      PGHERO_PASSWORD:

      CACHE_BACKEND:
      CACHE_LOCATION:
      CACHE_CLIENT_CLASS:

      MINIO_ENDPOINT:
      MINIO_USE_HTTPS:
      MINIO_ACCESS_KEY:
      MINIO_SECRET_KEY:
      MINIO_PRIVATE_BUCKETS:
      MINIO_PUBLIC_BUCKETS:
      MINIO_EXTERNAL_ENDPOINT:
      MINIO_EXTERNAL_ENDPOINT_USE_HTTPS:
      MINIO_ATTACHMENTS_BUCKET:
      MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN_ATTACHMENTS:

      CELERY_BROKER_URL:
      CELERY_RESULT_BACKEND:

      ELASTICSEARCH_HOST:

      GITHUB_CLIENT_ID:
      GITHUB_SECRET_KEY:
  tms-base:
    extends:
      service: tms

    build:
      additional_contexts:
        app: docker-image://tms