services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "8443:8443"
    networks:
      - caddy
    labels:
      caddy.https_port: 8443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
  email:
      image: rnwood/smtp4dev
      init: true
      restart: on-failure
      volumes:
        - smtp_data:/smtp4dev
      networks:
        - caddy
      ports:
        - "25:25"
      labels:
        caddy: email.lvh.me
        caddy.tls: internal
        caddy.reverse_proxy: "email:80"
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - caddy
  pghero:
    image: ankane/pghero
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - PGHERO_USERNAME
      - PGHERO_PASSWORD
    networks:
      - caddy
    labels:
      caddy: pghero.lvh.me
      caddy.tls: internal
      caddy.reverse_proxy: "pghero:8080"
  redis:
    image: redis:8.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - caddy
volumes:
  smtp_data: {}
  caddy_data: {}
  postgres_data: {}
networks:
  caddy: {}