name: Lint with Ruff

on:
  pull_request:
    branches:
      - main
    paths:
      - "."
  push:
    branches:
      - main
    paths:
      - "."

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.4"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: |
          uv sync --project . --dev

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Run Ruff
        run: |
          uv run --project . ruff check .

      - name: Run tests
        run: |
          uv run python manage.py test --settings=tms.test_settings
